### ISSUE TITLE
Bracket highlighting and auto-indentation is broken after the most recent update.

### ISSUE THREAD

**Issue by Chewyshoot** [cwtools/cwtools-vscode#101]
Built in snippets/autofill no longer formatting and brackets are no longer linked (and also are all white now)

![image](https://github.com/cwtools/cwtools-vscode/assets/104266501/78898dd0-55e2-453d-a3c6-7a77ab3078e0)

**Comment by tboby** [comment]
Thanks for raising this, should be fixed shortly, pipeline running: https://github.com/cwtools/cwtools-vscode/actions/runs/7304354370
