### ISSUE TITLE
[HOI4] False Error when using 'num_faction_members' "Expecting an integer, got from.num_faction_members"

### ISSUE THREAD

**Issue by Wehrmachtserdbeere** [cwtools/cwtools-vscode#107]
In an Event's ai_chance, when trying to compare faction members, it gives an incorrect error.

```
			modifier = {
				add = -10
				num_faction_members > FROM.num_faction_members
			}
```

I checked and it does not cause an in-game error.

**Comment by Pelmen323** [comment]
I've updated config to resolve the issue. The fix will be available in https://github.com/cwtools/cwtools-hoi4-config/pull/189

Please use https://github.com/cwtools/cwtools-hoi4-config/issues to report hoi4-related issues
