### ISSUE TITLE
[Suggestion] Add support to consider certain filepaths as part of canon "vanilla" game folder.

### ISSUE THREAD

**Issue by PPsyrius** [cwtools/cwtools-vscode#108]
This should really help narrow down false positive errors when developing submods. This is much preferable to lumping parent(s) mod files into a specific game vanilla folder (which is not ideal).

Something like this (Mod 2, which loads after, will overwrite any Mod 1 file with the same name)
![image](https://github.com/cwtools/cwtools-vscode/assets/19505219/e5404cae-8fd7-4bf4-ae0b-e54783b1a9da)

This might be more of a long-term improvement goal than anything - I hope this gets implemented someday.

**Comment by tboby** [comment]
This is already supported by VS Code. Simply create a workspace and add both mods: load order will automatically be determined and matching files overwritten.
