### ISSUE TITLE
Hoi4 ideas not treated as symbols

### ISSUE THREAD

**Issue by inflation** [cwtools/cwtools-vscode#34]
Hoi4 ideas are stored like:
```
ideas = {
    country = {
        idea_1 = {
            ...
        }
    }
}
```

It only recognizes `ideas` as a symbol, not processing under the structure.

**Comment by noah1gamble** [comment]
I assume this is because Hearts of Iron IV is not yet supported.

**Comment by Makkkkus** [comment]
> 
> 
> I assume this is because Hearts of Iron IV is not yet supported.

It is

**Comment by noah1gamble** [comment]
> 
> 
> > I assume this is because Hearts of Iron IV is not yet supported.
> 
> It is

I said that quite some time ago.. 

"noah1gamble commented on Jul 13, 2020"

**Comment by Makkkkus** [comment]
Why is this issue still open, please close it @inflation
