### ISSUE TITLE
High Memory usage

### ISSUE THREAD

**Issue by noah1gamble** [cwtools/cwtools-vscode#45]
![image](https://user-images.githubusercontent.com/11571144/99878906-9bb10f00-2bd6-11eb-8954-8904be6140c7.png)

There is no reason for this to be using MORE RAM than the game itself.

**Comment by tboby** [comment]
Sure there is, that's fairly standard for IDEs.
It's maybe 50% high compared to industry leading tools (e.g. Visual Studio with C# or F#), but I'm one person not a team of developers working on this full-time. :)

I'll happily accept any PRs that improve memory usage.

**Comment by noah1gamble** [comment]
I can provide no input on PRs for performance increases, but regardless it would be nice to see it reduced if it is not already.
