### ISSUE TITLE
Feature Request: Make CWTools work outside the default mod path

### ISSUE THREAD

**Issue by Zetabite** [cwtools/cwtools-vscode#54]
I would suggest making it possible for CWTools to operate from outside of the default mod folder. Using it outside currently makes CWTools unable to recognize issues. Only moving to the default location fixes this. I see it as problematic, as Paradox Launcher and Steam to a degree can mess with that location, which i find unreasonable for developing a consistent mod. So i request this to be more flexible, so corruption due to Paradox Launcher or Steam acting up cant happen.

**Comment by Zetabite** [comment]
I made an interesting discovery. After opening the mod once in the default mod folder, it worked in my alternative folder. Maybe not feature request but bug report?

**Comment by tboby** [comment]
@Zetabite It works in any folder that has the game name somewhere in the path.

E.g. D:\Git\Stellaris\my_mod will work fine.

You should be using git so you shouldn't be worrying about corruption :)
