### ISSUE TITLE
New EU4 1.32 TAGs missing

### ISSUE THREAD

**Issue by noah1gamble** [cwtools/cwtools-vscode#55]
ISR, GZI , etc, are missing and throwing false errors.

**Comment by F1r3Pr1nc3** [comment]
For what, for which game?

**Comment by noah1gamble** [comment]
> For what, for which game?

EU4, latest update 1.32

**Comment by maxice8** [comment]
This should be fixed as the list of country tags is generated dynamically by looking at all files in `common/country_tags`
