### ISSUE TITLE
New DLC problems HoI4

### ISSUE THREAD

**Issue by cheeems02** [cwtools/cwtools-vscode#56]
New DLC got released for hoi4 and now all new commands aren't recognized by the extension, I hope it is fixed soon, I can't work without your extension ❤️ :trollface: 
I hope I didn't miss the repo

**Comment by noah1gamble** [comment]
Change title to include HOI4 since this tool supports multiple paradox games.

**Comment by barty5260** [comment]
![image](https://user-images.githubusercontent.com/62222839/147136394-29a07ee1-5e89-4ed6-8ad1-406fa75ffb68.png)
I'm having the same problem but with many commands that existed before NSB and that worked well with the extension.

**Comment by barty5260** [comment]
I had a similar issue but It turns out it was an incompatibility with another extension.
