### ISSUE TITLE
HOI4 unexpected error

### ISSUE THREAD

**Issue by lxphilipp** [cwtools/cwtools-vscode#60]
![image](https://user-images.githubusercontent.com/94622152/151666484-bd92a0d7-c780-4922-9ba5-912082a03a34.png)
Appears anywhere for recruit_character, even in game files, dunno where to post this

**Comment by Pelmen323** [comment]
Was fixed long ago

Please report hoi4 issues here https://github.com/cwtools/cwtools-hoi4-config/issues
