### ISSUE TITLE
EU4 - simple Localisation issue

### ISSUE THREAD

**Issue by noah1gamble** [cwtools/cwtools-vscode#61]
![image](https://user-images.githubusercontent.com/11571144/152052423-433edddd-ccf1-4b09-944c-baa4898a1fc3.png)

**Comment by noah1gamble** [comment]
emberor_alert should be emperor_alert

**Comment by maxice8** [comment]
The correct repo would be https://github.com/cwtools/cwtools-eu4-config, and this was fixed recently with https://github.com/cwtools/cwtools-eu4-config/commit/c5c2b50b2244b0cdd99fe7bd17d35cd9d2d69f4d
