### ISSUE TITLE
Add setting to disable formatting on save

### ISSUE THREAD

**Issue by maxice8** [cwtools/cwtools-vscode#67]
I am currently exploring bugs in other people's mods and cwtools keeps formatting the whole file when I'm just modifying some small numbers and saving, it makes it harder to track changes with `git`.

**Comment by tboby** [comment]
cwtools-vscode shouldn't be triggering whole file formatting automatically.

Have you enabled the setting globally for VS Code? If so, you might want to consider disabling it for now, or enabling it on a per workspace basis.

The setting id is `editor.formatOnSave`.  File -> Preferences -> Settings, then search for "Editor: Format on save".

**Comment by maxice8** [comment]
Thank you! I have disabled it for now.
