### ISSUE TITLE
Support Extension in Open VSX Registry

### ISSUE THREAD

**Issue by Strix12** [cwtools/cwtools-vscode#69]
For those of us who dislike the in-built telemetry included in Microsoft's version of VSCode, there is an open source version called VSCodium. However, this extension is not included in their extension registry. Is it possible to add this extension to that registry?

Link: https://open-vsx.org/

**Comment by BrickWithHat** [comment]
I use VScodium, what you can do is download the .vsix file and the install it under the extensions tab my selecting 'Install from VSIX...'. The downside of it is that updates are entirely manual so you have to go get them yourself.
