### ISSUE TITLE
HoI4: scoped_play_song highlighted as "unexpected in scope" error when used correctly

### ISSUE THREAD

**Issue by SNBeast** [cwtools/cwtools-vscode#75]

**Comment by Pelmen323** [comment]
No longer actual
![Screenshot (4410)](https://github.com/cwtools/cwtools-vscode/assets/43440389/ebb13a52-2f45-423c-a6a5-0a76a694cc28)

Please report hoi4 issues here https://github.com/cwtools/cwtools-hoi4-config/issues
