### ISSUE TITLE
Suggestions/Errors

### ISSUE THREAD

**Issue by Thanasis09** [cwtools/cwtools-vscode#87]
For all Suggestions, I'm talking about hoi4
Suggestions:
1) Make on_actions autocompletion work, it has stopped working and if I open an on_action file and write something there, the extension then doesn't work for any file
2) add the `is_embargoing = TARGET` trigger
3) Make `title` and `desc` autocomplete with `country_event` and all other events, because both are required for an event to display, could also extend this by adding the `is_triggered_only = yes` and an `option = { ... }` block, because they are all used most of the times. Another Suggestion for events would be so that when in the `id` I type for example `italy.1` the title would automatically convert to `italy.1.t` and desc to `italy.1.d`, it would save lots of time.
4) Fix the `scrollbarType` in `.gui` files not being recognised when in an `instantTextBoxType`
5) When in loc files, if there isn't an `l_english` at the start, and there are loc entries, make it so an error is displayed about this. Could also make it so if a `.yml` file in the `localisation` folder doesn't have `l_english` at its end, it also throws this error

Errors:
1) A lot of times, the extension doesn't load and requires lots of reloads
2) Since about 3 days ago, it asks me to select the vanilla installation folder, I do, and then it sends 2 messages immediately: 
One that says: "Generating Vanilla Cache"
And another that says:  "Please Select Vanilla Installation folder". Even If I redo it, it still doesn't stop asking me
3) Not sure if it is an error, but the extension is really really slow. It needs to be improved performance-wise

**Comment by Pelmen323** [comment]
1.
![Screenshot (4407)](https://github.com/cwtools/cwtools-vscode/assets/43440389/7842ced1-8419-40f5-a244-cf902dffec1e)

2.
![Screenshot (4408)](https://github.com/cwtools/cwtools-vscode/assets/43440389/31edfae1-ae42-4b9a-8827-cee85f180e5e)

4.
![Screenshot (4409)](https://github.com/cwtools/cwtools-vscode/assets/43440389/a1abf571-3d8e-47b3-9421-6570c46b8be4)


Please report hoi4 errors here https://github.com/cwtools/cwtools-hoi4-config/issues

**Comment by Thanasis09** [comment]
@Pelmen323 the fixes were recent; at the time the issue was written the pictures you posted weren't fixed. Thanks nonetheless

**Comment by Pelmen323** [comment]
@Thanasis09 no worries. I'm maintaining hoi4 config and decided to check if there are any relevant issues on other tracker.
If you'll encounter other hoi4 problems, please report them using the link above, good luck!
